### ISSUE TITLE
rtop: asn1: structure error: length too large

### ISSUE THREAD

**Issue by fniephaus** [rapidloop/rtop#3]
Hi there,

I tried to build this on OS X 10.10.3 and everything went well. But now when I try to connect to a remote server, I always get:

`rtop: asn1: structure error: length too large`

What is going wrong here?

Regards,
Fabio

**Comment by runar** [comment]
I am experiencing the same error, and after some research, I think it has something to do with the SSH key being password protected and `rtop` not cooperating with `ssh-agent`.

See these issues on other projects written in Go for similar errors:

- https://github.com/shazow/ssh-chat/issues/75
- https://github.com/mitchellh/packer/issues/1445

**Comment by lodestone** [comment]
:+1: 

Having this issue as well. Mac OSX Yosemite.

**Comment by mattiasgeniar** [comment]
Just to confirm, same issue here, with a password-protected SSH key.

```
 ./rtop host
rtop: asn1: structure error: length too large
```

**Comment by runar** [comment]
I’m still having this issue. Is there something else needed to be done on my end?

**Comment by fniephaus** [comment]
Same here.

**Comment by JamesMura** [comment]
same here

**Comment by aequitas** [comment]
Same here, running OSX Yosemite.

**Comment by marthjod** [comment]
Same here, Ubuntu 14.10. Ran `ssh-add` before.

**Comment by slava-vishnyakov** [comment]
Same here with password-protected key, `git pull; make` didn't help.

```rtop: asn1: structure error: length too large```

**Comment by mbranyon** [comment]
I fixed this error by changing the order in which auth methods are added in src/sshhelper.go
```ShellSession
$ git diff src/sshhelper.go
diff --git a/src/sshhelper.go b/src/sshhelper.go
index 4119c79..cf79de4 100644
--- a/src/sshhelper.go
+++ b/src/sshhelper.go
@@ -113,9 +113,9 @@ func addPasswordAuth(auths []ssh.AuthMethod) []ssh.AuthMethod {
 
 func sshConnect(user, addr, keypath string) (client *ssh.Client) {
        auths := make([]ssh.AuthMethod, 0, 2)
-       auths = addAgentAuth(auths)
-       auths = addKeyAuth(auths, keypath)
+    auths = addKeyAuth(auths, keypath)
        auths = addPasswordAuth(auths)
+       auths = addAgentAuth(auths)
 
        config := &ssh.ClientConfig{
                User: user,
```

**Comment by fniephaus** [comment]
How about a new Pull Request? This issue is already closed :cry:

**Comment by runar** [comment]
Changing the order of the auth methods did not solve the error for me. How is your private key encrypted, @mbranyon? Are you using `ssh-agent` or the OS X Keychain?

**Comment by mbranyon** [comment]
I might have posted this to the wrong issue. I am not using OS X, I am in linux. This is using ssh-agent.

**Comment by fniephaus** [comment]
Yep, looks like you did. We're looking for a solution for Yosemite 10.10.x :stuck_out_tongue_winking_eye:

**Comment by marthjod** [comment]
@fniephaus Well, not only. Ultimately, this should work for both MacOS and Linux.

**Comment by fniephaus** [comment]
@marthjod you're right. I was just talking about this particular issue...

**Comment by mdevan** [comment]
Try with the latest commit ba5b35e. This improves the auth method handling.

**Comment by fniephaus** [comment]
Works like a charm. Thanks!

**Comment by slava-vishnyakov** [comment]
Yay! Thanks for the fix!
