### ISSUE TITLE
Unable to connect:  tags don't match

### ISSUE THREAD

**Issue by zachberger** [rapidloop/rtop#4]
```
rtop: asn1: structure error: tags don't match (16 vs {class:0 tag:3 length:120 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 set:false omitEmpty:false} pkcs1PrivateKey @
```

**Comment by forrestsun** [comment]
me too
```bash
Linux 390 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
 ./rtop -i ~/.ssh/id_rsa user1@192.168.1.110:2000
rtop: asn1: structure error: tags don't match (16 vs {class:3 tag:1 length:5 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 set:false omitEmpty:false} pkcs1PrivateKey @2

```

**Comment by mdevan** [comment]
Fixed in ed16e84.

**Comment by 1st8** [comment]
Same error for me on current master.

**Comment by KKostya** [comment]
Problem persists (same error message) for me whatever arguments I use.

**Comment by esbenp** [comment]
Same for me.

```rtop: asn1: structure error: tags don't match (16 vs {class:2 tag:23 length:6 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 set:false omitEmpty:false} pkcs1PrivateKey @2```

**Comment by zachberger** [comment]
Works for me now.

**Comment by mdevan** [comment]
Try with the latest commit ba5b35e. This improves the auth method handling.
